### PR TITLE
Erik update textinputs

### PR DESCRIPTION
**Pull request by EHaake**
Mainly some UI Tweaks.

1) Update Login and Register Screen inputs for design and add icons
2) Add username field to Register Screen
3) On login screen change email to username
4) On Feed screen update Search bar styles with icons and clear button functionality

### CODE REVIEW

**Comment by EHaake** [comment]
Login and Register screen icons not looking right on my iPhone. Need to fix

**Comment by robalty** [comment]
Fields look good on my Android phone. Post creates successfully. Approved.

**Comment by robalty** [comment]
I said approved!!

**Review by robalty — APPROVED** [review]
I was approving in the wrong place...

**Pull request merged**
