### PR TITLE
Geolocation frontend and backend

### PR DESCRIPTION
**Pull request by SimonBartonPSU**
This is a rebase of Michael's branch with backend code for #178 #225 #226 committed on top. I did this again because #227 got some invalid code related to `Switch`es on posting creation screen.

Biggest problem: Cannot migrate the database due to `Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.`

At this point, I'm a bit confused as to our plan on location services. Perhaps this thread might be a good place for us to discuss and have things thoroughly documented.

It seems like we want :

- user profile contain a user's location (sent in POST during registration)

- user's location is what is assigned to the postings they create (handled by backend by pulling the User's associated location from their profile and copying that to the posting?)

- Communties have a location (Manually setup by us ?)

Is this correct?

### CODE REVIEW

**Comment by seansisson** [comment]
The things related to location you mentioned are correct @SimonBartonPSU, or at least from my understanding of where we're headed. Will test this branch now.

**Comment by SimonBartonPSU** [comment]
Huzzah!!!!! Migrations worked. Location is passed on profile creation and stored with a user's profile.

When a posting is created, saved location is attached to a posting.

If everyone can give this a thorough test, perhaps try to break things, we can verify that this code is good.

**Comment by EHaake** [comment]
Everything I tried worked for me on both Android emulator and iOS. 

Tried:
1) Registering new profile
2) Logging out
3) Logging back in
4) Creating a new Posting
5) Editing the Posting
6) Joining communities
7) Leaving communities
8) Editing Profile

**Review by EHaake — DISMISSED** [review]
Works for me! Tried all features on both iOS and Android Emulator

**Comment by SimonBartonPSU** [comment]
Hmm interesting. Not sure why my iOS was denying network requests last week, but it is working now.

Glad it's working for now, I'll still try to get HTTPS working regardless.

**Review by seansisson — DISMISSED** [review]
Confirmed all features work as expected on android. Good stuff :)

**Review by seansisson — DISMISSED** [review]
Still lookin' good, just added the migration. Good catch -- this saves a borked deploy :)

**Review by EHaake — APPROVED** [review]
Is good

**Pull request merged**
