### PR TITLE
Camera upload

### LINKED ISSUE #131: Add ability for to use camera for adding images
# Plan/Proposed Change
Currently the user only has the option to select an existing image in their library when adding an image to their new posting. Modify it so that the user can select between choosing a library image and using the camera.

The visual design of the screen shouldn't be modified, but once the image icon is tapped, the user should be able to select between using the camera and selecting a library image.

### PR DESCRIPTION
**Pull request by KipTheTurtlebear**
Added Camera Upload functionality, tested on iOS and Android

Also made a slight change to Item Description keyboard type

Closes #131

### CODE REVIEW

**Review by SimonBartonPSU — DISMISSED** [review]
Looks excellent. Works for me locally on iOS, still fussing with my android emulator but sounds like that's good.

Nice work :+1:

**Comment by EHaake** [comment]
Works for me on both iOS and Android!

**Comment by EHaake** [comment]
Shorten button text so they all appear on one row on Android: 
Screenshot_20200703-184356

**Review by EHaake — DISMISSED** [review]
Looks good!

**Pull request merged**
