### PR TITLE
Django file names

### LINKED ISSUE #59: Change Django File Structure
# Plan/Proposed Change
Change 'todoapi' and 'todoproj' to 'cgapi' and 'cgproj'

# Why is this important
Having a directory structure that reflects the actual project is a nice feature

### PR DESCRIPTION
**Pull request by SimonBartonPSU**
Resolves #59  everything is 'cgapi' and 'cgproj' now instead of todo, also couple nice to haves added for testing:

- Django accepts connections from private IP address blocks
- URL endpoint set as a const in App.js, so we only have to switch in one spot to connect local vs deployed (This can be automated soon with an environment var and Make commands, I think)
- Related to #51 : pre-push script now spawns the local docker containers in subshell and runs Postman tests against these (I think this makes sense because it would be new code being tested, not running existing tests against the existing deploy)

I would like to use this Pull Request to test #52 as well, when this is merged, new Google App Engine deploy happens. I think doing this with some hiccups can help figure out #25

### CODE REVIEW

**Comment by EHaake** [comment]
I noticed that while the new directories (cgapi and cgproj) were added, the old ones (todoapi and todoproj) are still there. Was this intentional?

**Review by EHaake — COMMENTED** [review]
When this is merged, are we expecting issues with the Google App Engine deployment or are we expecting everything to go smoothly?

**Comment by SimonBartonPSU** [comment]
If you're looking at the code locally, git may have cached the todo folders or something when switching branches. If you look at the files changed or the branch on GitHub, the todos are [gone](https://github.com/Capstone-SS-2020-PDX/Covid-19-MutualAid/tree/django-file-names/django)

I am expecting issues with the Cloud Build because I've never done it before (also the file name changes may mess with the schema), but I will troubleshoot via gcloud if there are issues

**Comment by EHaake** [comment]
Yeah I was only looking at it locally, so it clears that up. Since this has to do with the deployed model, perhaps we should have @robalty oversee this merge.

**Comment by robalty** [comment]
I'm updating the deployed databases, after which everything should be ok with this, but I'll come back and let you know once I've got it deployed.

**Comment by SimonBartonPSU** [comment]
shweeeeet. I'm hoping to get us to a point where we can merge new back end code and automatically:

- get a new django deploy
- cloudsql db instance gets a migration
- slack notification of success

The django deploy should already happen, 'cause I have a Cloud Build trigger enabled in our GCP project, but the automatic db migration I'm not so sure of

**Comment by robalty** [comment]
Automatic DB migration is harder since the GAE platform that the app is deployed on doesn't allow you to run scripts - I've just been running manage.py locally with the proxy every time. I'll see if I can find a way to make it happen though.

**Comment by SimonBartonPSU** [comment]
Hmmm yeah the only thing I could think of was figuring out how to make the migration run as part of the cloudbuild.yaml (which is what the Cloud Build trigger uses for deployment instructions).

Manually migrating via proxy isn't too big of a deal for now though. The automated migration could be another pull request later on

**Review by robalty — APPROVED** [review]
I made two small changes. First, I removed a couple surviving references to 'todoapi' in the migrations. Second, I changed the database name to reflect the 'cg___' naming scheme, and because it was easier than reconfiguring the old database. With those changes this code looks good, and deployed without a hitch, so it's got my approval!

**Comment by SimonBartonPSU** [comment]
Nice catch, ty

**Pull request merged**
