### PR TITLE
Erik fix update profile edit bug

### PR DESCRIPTION
**Pull request by EHaake**
Fix bug not allowing user to update profile data due to username apparently not being available.

Should be working on both iOS and Android

### CODE REVIEW

**Comment by SimonBartonPSU** [comment]
I'm not able to update the username:

image

Modal tells me that username is not available, but console says it is... 

image

I'm thinking maybe we shouldn't even allow users to change their username??

**Review by SimonBartonPSU — DISMISSED** [review]
I am able to update every aspect of a profile on iOS and Droid emulator, except for the username. Like I mentioned in my comments, maybe we don't allow that functionality? If we do or do not, we can address that specific piece in a new issue. This seems to resolve enough to warrant a merge.

I am approving, but it's getting to the point where I would feel more comfortable if multiple people took a look a things.  ¯\\_(ツ)_/¯

**Comment by alexandra-hanson** [comment]
I was unable to view the Profile screen page on my emulator, but I could see it when I ran expo on my phone. I was able to edit the profile and update all fields except for the username field; however, like Simon, when I attempt to update the username the pop up states "username not available", despite the console saying that it is available. Tested on my Google Pixel 3.

**Comment by robalty** [comment]
Yeah, I can't change my username either. It says the username is taken in the app even when it says it's available in console, like what happened to Simon. It does correctly identify when a username is taken - it told me that "erikh" wasn't available. I agree with the others though, I don't think we need to let people change their usernames so freely. Everything else updates just fine though.

**Comment by seansisson** [comment]
Currently running into an error loading a null object when trying to update profile, app is currently in a weird state, will update with progress

**Review by seansisson — APPROVED** [review]
Looks good to me, I was able to fix some of the issues I was having earlier, the profile edit screen works

**Comment by robalty** [comment]
Yeah, aside from the username thing I didn't have any problems, so I think this should be merged.

**Pull request merged**
