### PR TITLE
Address iOS login crash

### PR DESCRIPTION
**Pull request by EHaake**
### Fixes:
1) Fix issue when trying to submit empty login/register form via button. Now it doesn't even attempt the request if the fields are empty.
2) (Hopefully) improves AuthProvider by resolving promises and not setting app ready state until communities are retrieved either from server or local storage.

### Enhancements: 
1) Adds Next button functionality to ProfileCreationScreen (forgot to add in previous pull request).

### Not addressed:
1) Issue with iOS app crashing when login/register attempts are unsuccessful. I don't know why this is happening. It doesn't happen on my Android phone or android emulator so it seems that it is an iOS only issue.  Will definitely need investigating.

addressed in issue #214

### CODE REVIEW

**Comment by SimonBartonPSU** [comment]
When I attempt to login with known good credentials the app crashes. 
image

**Comment by SimonBartonPSU** [comment]
Yup, tested with a new account. I can login by registering, but once I logout and attempt to log back in, server gives 400 and app crashes. 

image

Sent out a request on slack for more testing / eyes on this code. Very important that our login functionality works.

**Comment by EHaake** [comment]
Yeah, this one might be a loss. I tried retooling the auth context to try and fix the iOS crashing issue but it seems it might have created more issues than it solved.

**Comment by alexandra-hanson** [comment]
Tested only on Android (Google Pixel 3), as I do not have access to iOS testing. I am able to log in and log out of an existing account without any issue. Trying to submit blank log in information yields a pop up message "fill out all details." Trying to submit nonexistent log in information does not allow me to log in, but also does not give a pop up message. Should we add a pop up message to notify the user the account does not exist or that there was a log in error?

**Comment by seansisson** [comment]
Similar story with me regarding Allie's comment. My iOS simulator needs updating and I'm trying to figure that out currently.

**Comment by EHaake** [comment]
Closing since we found a better way to do it.

**Pull request closed without merging**
