### PR TITLE
Erik add postings to context

### LINKED ISSUE #218: After Editing a Posting, updates should appear immediately
**Describe the solution you'd like**
If a posting is edited or deleted, the change isn't displayed either on the detail screen or in the feed screen until a pull-to-refresh is triggered manually by the user.  Modify this so that the detail is updated immediately after successful update/deletion.

**Describe alternatives you've considered**
Could potentially, after updating, navigate back to the feed screen and perform an automatic refresh of the data instead of needing to have the user trigger it manually.

### LINKED ISSUE #231: Add Postings to App Context
**Describe the solution you'd like**
Add the list of postings to the Global App Context so that they are easier to access and updates can be propagated to other screens.

**Reasons for this change**
We're constantly re-fetching all the postings from the server which is expensive and unnecessary.
Also, making updates to screens require re-fetching, including after favoriting or editing posts.  

**Additional context**
Adding Postings to the App context should make it simpler to perform auto updates on the various screens without requiring re-fetching all postings after certain actions are performed.

### PR DESCRIPTION
**Pull request by EHaake**
## Additions
1) Adds postings to app context so that all list screens share the same list of postings instead of fetching and maintaining their own copies
2) This allows changes to be updated reflected automatically in the lists, say when a posting is flagged, a user won't have to 'Pull to Refresh' on a list in order to see the changes ~~(except when changing search method)~~
3) Add Settings page where there is an option to change from Community Based search to Radius based search.  It defaults to community based search but when toggled, a radius slider will appear to allow the user to select the radius they want to search in (from 1 to 50 miles). ~~Going back to the Home screen, the user can pull to refresh to see the new set of Postings~~
Edit: When Search method is changed, the postings list should be automatically refreshed.
4) Add button in Title Bar of Profile Screen to update the user's location to their current location.
5) Add a map to Profile Screen so user knows where their home location is set.

## To Note
- Currently all List Screens share the same list of postings so if the Search method is changed then the shared list of postings will change. This means that navigating to 'My Postings' or 'Saved Postings' may not show the same postings (or anything at all) if the user is using the Radius method and those postings are outside their range.
- I hope to change this in the future but for now it will have to do.

- Please check to make sure these new features work as expected and in particular, that there are no crashes or unexpected behavior.

## Issues closed
closes #231 
closes #218

### CODE REVIEW

**Review by KipTheTurtlebear — DISMISSED** [review]
All is working well for me on Android

**Review by seansisson — DISMISSED** [review]
Features work as intended on Android :) Lots of great work went into this

**Review by SimonBartonPSU — DISMISSED** [review]
Nicely done. Lifting the state up, very React.

I tested very thoroughly on both platforms. On both existing user and a freshly made user:

- Created multiple postings
- Updated profile
- Update home location
- Flagged posting
- Favorited postings
- Viewed saved postings
- Edited my postings
- Tested the location vs community filtering (More effective on iOS for me, since I'm stuck with Palo Alto)

Overall, everything seems to be working well. The radius vs community is pretty slick, and it's nice to not have to refresh as much.

I did experience two crashes while using iOS, both of which occurred on the PostingCreationScreen and both were another `Malformed calls from JS: field sizes are different` error.

One instance was after I had the Expo app minimized for a while, I was on my mobile browser. When I returned to expo app and finished filling out posting, the app crashed right when I selected 'Camera' for my posting image option.

Second instance was weirder. I was editing the Count Input on PostingCreationScreen, I was trying to do the iOS press-and-hold, which brings up the magnifying glass, because I wanted to move my input to the right of the '1' rather than on the left. There was a short spazzy moment with the magnifying glass then got the error.

I was unable to replicate the crashes, even though I tried quite hard. I'm not too concerned about these because I haven't been able to replicate, but figured I'd report the findings. Most likely unrelated to the code in this PR as well.

**Comment by EHaake** [comment]
Thanks for posting your experience and thorough testing! Those errors are a little disconcerting but I wasn't able to reproduce on my iPhone. I think that the image/camera issues is an Expo thing and have no idea about the text input problem.

**Pull request merged**
