### PR TITLE
Erik add communities list

### LINKED ISSUE #211: Create Community List Page
# Plan/Proposed Change
Create a Page listing all Available communities. Will work like the posting list page where communities will be able to be searched through.  A community list item should have an icon that when tapped, will display a check mark, indicating that it has been selected.  A done button will then add all selected communities to the user profiles 'member_of' array.

# Why is this important
Users need a way to join multiple communities since that is kinda the point of the app.

### PR DESCRIPTION
**Pull request by EHaake**
## Additions
Big update!! 

1) Add communities Screen where you can view your communities
2) Add 'Join Communities' screen linked from the top right of the Communities screen where you can add and remove communities. Cannot remove home community on this screen since a user must have a home community.
3) Change pickers in Edit Profile Screen and Edit Posting Screen to only show communities that you are a member of.
4) Feed screen and community list screen will automatically update to reflect changes in member's communities.
For example, if you remove Montavilla from your communities, then navigating back to the Home/Feed screen will no longer show postings from Montavilla

## Please Note...
If you login with an older account, the feed screen and communities screen will initially show nothing since you don't have any communities in your profile's `member_of` list. To solve this, go to the add communities from the Communities screen and add one. This should populate your `member_of` list and therefore also your Communities list.

closes #211

### CODE REVIEW

**Review by seansisson — DISMISSED** [review]
Tested, confirmed that these features work on Android. I was able to join a different community and remove myself from other communities. This had the effect of changing the postings shown on the home screen.

In the communities screen, I noticed that the navigation stack is not at the bottom of the screen similar to the posting add screen, profile, and home page. 

Overall this looks great :) Approving

**Comment by SimonBartonPSU** [comment]
I think this needs a `git rebase master` getting crashes on testing.

**Review by SimonBartonPSU — DISMISSED** [review]
Tested thoroughly on Droid and iOS. Looks good!

**Review by SimonBartonPSU — APPROVED** [review]
Re-good after merge conflict fixes.

**Pull request merged**
